agent/quote/urls.py
from django.conf.urls import url
import agent.quote.views as views

urlpatterns = [
    url(r'^performance/(?P<pk>[0-9]+)/$', views.AgentPerformance.as_view()),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^new/$', views.new, name='new'),
    url(r'^completed/$', views.completed, name='completed'),
    url(r'^price/(?P<pk>[0-9]+)/$', views.Price.as_view(), name='price'),
    url(r'^price/$', views.Price, name='price_no_vars'),
]

config/urls.py
from django.conf.urls import include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^quote/', include('agent.quote.urls', namespace='quote')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

try:
    if settings.LOCAL:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
except AttributeError:
    # don't load the debug toolbar URLs
    pass

agent/quote/models.py
from django.db import models


class Customer(models.Model):
    """
        Model for Customer Attributes
    """
    agent = models.ForeignKey('Agent')
    name = models.CharField(max_length=128)

    HOMEOWNER = 'hom'
    OTHER = 'oth'

    TYPE_CHOICES = (
        (HOMEOWNER, 'Homeowner'),
        (OTHER, 'Other'),
    )
    customer_type = models.CharField(
        max_length=3,
        choices=TYPE_CHOICES,
        default=HOMEOWNER,
    )


class Quote(models.Model):
    """
        Model for Quote Attributes
    """
    customer = models.ForeignKey('Customer')
    address = models.CharField(max_length=128)
    new_quote = models.BooleanField(default=True)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=True,
        null=True,
    )
    date = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)


class Agent(models.Model):
    """
        Model for Agent Attributes
    """
    name = models.CharField(max_length=128)

agent/quote/forms.py
from django import forms


class PriceForm(forms.Form):
    """ Price form to take agent input for quote value """
    price_form = forms.DecimalField(label='Enter Quote Value ')

agent/quote/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import permissions

from django.shortcuts import render
from django.views import View

from .forms import PriceForm
from .models import Quote
from .utils import create_non_naive_date_time, create_date_list, build_api_result


def dashboard(request):
    """ Dashboard view to provide overview to agents
        Args:
            request <request object>: request object
        Returns:
            Dashboard template with new_quotes and completed_quotes template variables
    """
    new_quotes = Quote.objects.filter(new_quote=True)
    completed_quotes = Quote.objects.filter(new_quote=False)
    return render(
        request,
        'quote/dashboard.html',
        {'new_quotes': new_quotes, 'completed_quotes': completed_quotes}
    )


def new(request):
    """ New quotes view to provide current new quotes to agents
        Args:
            request <request object>: request object
        Returns:
            New quotes template with new_quotes template variable
    """
    new_quotes = Quote.objects.filter(new_quote=True)
    return render(request, 'quote/new.html', {'new_quotes': new_quotes})


def completed(request):
    """ Completed quotes view to provide completed quotes to agents
        Args:
            request <request object>: request object
        Returns:
            Completed quotes template with new_quotes and completed_quotes template variables
    """
    new_quotes = Quote.objects.filter(new_quote=True)
    completed_quotes = Quote.objects.filter(new_quote=False)
    return render(
        request,
        'quote/completed.html',
        {'completed_quotes': completed_quotes, 'new_quotes': new_quotes}
    )


class Price(View):
    """ Price CBV to allow agents to view quote details and enter quote values """
    def get(self, request, pk):
        """ View to allow agents to visualize quote details
            Args:
                request <request object>: request object
                pk <int>: primary key of quote to be visualized
            Returns:
                Quote detail template with price_form, quote, and new_quote template variables
        """
        new_quotes = Quote.objects.filter(new_quote=True)

        quote = Quote.objects.get(id=pk)
        quote.start_time = create_non_naive_date_time()
        quote.save()

        price_form = PriceForm()

        return render(
            request,
            'quote/price.html',
            {'price_form': price_form, 'quote': quote, 'new_quotes': new_quotes}
        )

    def post(self, request, pk):
        """ View to allow agents to enter quote value for a specific quote
            Args:
                request <request object>: request object
                pk <int>: primary key of quote to be adjusted with added price value
            Returns:
                New quotes template with new_quote template variable
        """
        new_quotes = Quote.objects.filter(new_quote=True)

        price_form = PriceForm(request.POST)
        if price_form.is_valid():
            price = price_form.cleaned_data['price_form']

        quote = Quote.objects.get(id=pk)
        quote.new_quote = False
        quote.price = price
        quote.end_time = create_non_naive_date_time()
        quote.save()

        return render(request, 'quote/new.html', {'new_quotes': new_quotes})


class AgentPerformance(APIView):
    """
    Agent Performance Information From Quote Data
    """
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get(self, request, pk, format=None):
        """ API endpoint to allow for collection of agent performance data
            Args:
                request <request object>: request object
                pk <int>: primary key of agent to be assessed
            Returns:
                JSON response of agent performance data
        """
        agent_quotes = Quote.objects.filter(new_quote=False).filter(customer__agent=pk)
        date_list = create_date_list(agent_quotes)
        api_result = build_api_result(date_list, pk)
        return Response(api_result)

agent/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Agent Platform</title>
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'agent/img/logo.jpg' %}">
        <link href="{% static 'agent/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'agent/css/startmin.css' %}" rel="stylesheet">
        <link href="{% static 'agent/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'quote:dashboard' %}">AgentApp</a>
                </div>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-right navbar-top-links">
                    <li class="dropdown navbar-inverse">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-bell fa-fw"></i> <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-alerts">
                            <li>
                                <a href="{% url 'quote:new' %}">
                                    {% block notifications %}
                                    {% endblock notifications %}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> John Hanks <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                            </li>
                            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="#"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                            </li>
                        </ul>
                    </li>
                </ul>

                <div class="navbar-default sidebar" role="navigation">
                    <div class="sidebar-nav navbar-collapse">
                        <ul class="nav" id="side-menu">
                            <li class="sidebar-search">

                            </li>
                            <li>
                                <a href="{% url 'quote:dashboard' %}" class="active"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                            </li>
                            <li>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href="{% url 'quote:new' %}">New Quotes</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'quote:completed' %}">Completed Quotes</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% block content %}
            {% endblock %}
        <script src="{% static 'agent/js/jquery.min.js' %}"></script>
        <script src="{% static 'agent/js/bootstrap.min.js' %}"></script>
    </body>
</html>

agent/templates/quote/completed.html
{% extends 'core/base.html' %}

{% block notifications %}
<div>
    <i class="fa fa-comment fa-fw"></i> You have {{new_quotes.count}} New Quote(s)
</div>
{% endblock notifications %}

{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Completed Quotes</h1>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Completed Quotes
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Address</th>
                                <th>Customer Type</th>
                                <th>Quote Price</th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for completed_quote in completed_quotes %}
                          <tr>
                              <td>{{completed_quote.id}}</td>
                              <td>{{completed_quote.customer.name}}</td>
                              <td>{{completed_quote.address}}</td>
                              <td>{{completed_quote.customer.customer_type}}</td>
                              <td>{{completed_quote.price}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

agent/templates/quote/dashboard.html
{% extends 'core/base.html' %}

{% block notifications %}
<div>
    <i class="fa fa-comment fa-fw"></i> You have {{new_quotes.count}} New Quote(s)
</div>
{% endblock notifications %}

{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Quote Management Dashboard</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-comments fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{new_quotes.count}}</div>
                            {% if new_quotes.count == 1 %}
                              <div>New Quote!</div>
                            {% else %}
                              <div>New Quotes!</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <a href="{% url 'quote:new' %}">
                    <div class="panel-footer">
                        {% if new_quotes.count == 1 %}
                          <span class="pull-left">View Quote</span>
                        {% else %}
                          <span class="pull-left">View Quotes</span>
                        {% endif %}
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6">
            <div class="panel panel-green">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-tasks fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge">{{completed_quotes.count}}</div>
                            {% if completed_quotes.count == 1 %}
                              <div>Completed Quote!</div>
                            {% else %}
                              <div>Completed Quotes!</div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <a href="{% url 'quote:completed' %}">
                    <div class="panel-footer">
                        {% if completed_quotes.count == 1 %}
                          <span class="pull-left">View Quote</span>
                        {% else %}
                          <span class="pull-left">View Quotes</span>
                        {% endif %}
                        <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>

                        <div class="clearfix"></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                New Quotes
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Address</th>
                                <th>Customer Type</th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for new_quote in new_quotes %}
                          <tr>
                              <td>{{new_quote.id}}</td>
                              <td>{{new_quote.customer.name}}</td>
                              <td>{{new_quote.address}}</td>
                              <td>{{new_quote.customer.customer_type}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Completed Quotes
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Address</th>
                                <th>Customer Type</th>
                                <th>Quote Price</th>
                            </tr>
                        </thead>
                        <tbody>
                          {% for completed_quote in completed_quotes %}
                          <tr>
                              <td>{{completed_quote.id}}</td>
                              <td>{{completed_quote.customer.name}}</td>
                              <td>{{completed_quote.address}}</td>
                              <td>{{completed_quote.customer.customer_type}}</td>
                              <td>${{completed_quote.price}}</td>
                          </tr>
                          {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

agent/templates/quote/new.html
{% extends 'core/base.html' %}

{% block notifications %}
<div>
    <i class="fa fa-comment fa-fw"></i> You have {{new_quotes.count}} New Quote(s)
</div>
{% endblock notifications %}

{% block content %}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">New Quotes</h1>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Click to start quote
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Full Name</th>
                                <th>Address</th>
                                <th>Customer Type</th>
                                <th>Start</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for new_quote in new_quotes %}
                              <tr>
                                  <td>{{new_quote.id}}</td>
                                  <td>{{new_quote.customer.name}}</td>
                                  <td>{{new_quote.address}}</td>
                                  <td>{{new_quote.customer.customer_type}}</td>
                                  <td><a href="{% url 'quote:price' pk=new_quote.id %}">Start Quote!</a></td>
                              </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
</div>
{% endblock %}

agent/templates/quote/price.html
{% extends 'core/base.html' %}

{% block notifications %}
<div>
    <i class="fa fa-comment fa-fw"></i> You have {{new_quotes.count}} New Quote(s)
</div>
{% endblock notifications %}

{% block content %}
<div id="page-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Quote Information</h1>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                Full Name
                            </div>
                            <div class="panel-body">
                                <p>{{quote.customer.name}}</p>
                            </div>
                            <div class="panel-footer">
                                Customer Full Name
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="panel panel-green">
                            <div class="panel-heading">
                                Address
                            </div>
                            <div class="panel-body">
                                <p>{{quote.address}}</p>
                            </div>
                            <div class="panel-footer">
                                Customer Address
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                Type
                            </div>
                            <div class="panel-body">
                                <p>{{quote.customer.customer_type}}</p>
                            </div>
                            <div class="panel-footer">
                                Customer Type
                            </div>
                        </div>
                    </div>
                </div>
                <form action="{% url 'quote:price' pk=quote.id %}" method="post">
                  {{ price_form }}
                  {% csrf_token %}
                  <input type="submit" value="Submit" name="submit" class="btn btn-primary">
                </form>
{% endblock %}